/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ObsidianTestPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/ui/DashboardView.ts
var import_obsidian = require("obsidian");

// src/services/formatter.ts
function formatNotesForLLM(notes) {
  let prompt = "Generate test questions based on the following notes.\n\n";
  notes.forEach((note) => {
    prompt += `### Note: ${note.filePath}
`;
    prompt += `Content:
${note.content}

`;
  });
  prompt += "Ensure that the test questions are relevant to the content and test key concepts.";
  return prompt;
}

// src/services/llm.ts
var OPENAI_API_URL = "https://api.openai.com/v1/chat/completions";
var ANTHROPIC_API_URL = "https://api.anthropic.com/v1/messages";
var DEEPSEEK_API_URL = "https://api.deepseek.com/v1/chat/completions";
var MISTRAL_API_URL = "https://api.mistral.ai/v1/chat/completions";
var ContextLengthExceededError = class extends Error {
  constructor(message) {
    super(message);
    this.name = "ContextLengthExceededError";
  }
};
function getApiKey(provider, apiKeys) {
  return apiKeys[provider] || "";
}
async function generateTestQuestions(indexedNotes, provider, apiKeys, models, ollamaSettings) {
  const apiKey = getApiKey(provider, apiKeys);
  const model = (models == null ? void 0 : models[provider]) || getDefaultModel(provider);
  if (provider !== "ollama" && !apiKey) {
    throw new Error(`Missing API key for ${provider}! Please set it in the plugin settings.`);
  }
  const notesPrompt = formatNotesForLLM(indexedNotes);
  const systemInstructions = `
You are a helpful AI that generates test questions from user study notes.
We want each question to end with "(1)", "(2)", or "(3)" to show how many marks it is worth.
Correspondingly, the "type" field is "short" (1 mark), "long" (2 marks), or "extended" (3 marks).

Return JSON in this shape (no extra keys, no markdown fences):
{
  "description": string,
  "questions": [
    { "question": "What is X? (1)", "type": "short" },
    { "question": "Explain Y in detail. (2)", "type": "long" },
    { "question": "Discuss Z thoroughly with examples. (3)", "type": "extended" }
  ]
}
`.trim();
  try {
    let responseData;
    switch (provider) {
      case "openai":
        responseData = await callOpenAI(systemInstructions, notesPrompt, apiKey, model);
        break;
      case "anthropic":
        responseData = await callAnthropic(systemInstructions, notesPrompt, apiKey, model);
        break;
      case "deepseek":
        responseData = await callDeepSeek(systemInstructions, notesPrompt, apiKey, model);
        break;
      case "gemini":
        responseData = await callGemini(systemInstructions, notesPrompt, apiKey, model);
        break;
      case "mistral":
        responseData = await callMistral(systemInstructions, notesPrompt, apiKey, model);
        break;
      case "ollama":
        const ollamaUrl = (ollamaSettings == null ? void 0 : ollamaSettings.url) || "http://localhost:11434";
        responseData = await callOllama(systemInstructions, notesPrompt, model, 500, ollamaUrl);
        break;
      default:
        throw new Error(`Unsupported provider: ${provider}`);
    }
    return parseTestQuestionsResponse(responseData);
  } catch (error) {
    if (error instanceof ContextLengthExceededError) {
      throw error;
    }
    if (error instanceof Error && (error.message.includes("context_length_exceeded") || error.message.includes("maximum context length"))) {
      throw new ContextLengthExceededError(
        "The document is too large for the model's context window. Please split your document into smaller sections."
      );
    }
    throw error;
  }
}
async function markTestAnswers(noteContent, qnaPairs, provider, apiKeys, models, ollamaSettings) {
  const apiKey = getApiKey(provider, apiKeys);
  const model = (models == null ? void 0 : models[provider]) || getDefaultModel(provider);
  if (provider !== "ollama" && !apiKey) {
    throw new Error(`Missing API key for ${provider}! Please set it in the plugin settings.`);
  }
  const systemMessage = `
You are a helpful AI that grades user answers based on the provided source text.
A question might have (1), (2), or (3) to indicate mark weighting. For each answer, you need to return:
  - questionNumber: The question number (starting from 1)
  - marks: How many marks earned (0 to maxMarks)
  - maxMarks: Maximum possible marks for this question (1, 2, or 3)
  - feedback: A brief explanation of the grading

Output must be a JSON array with these fields only.
`.trim();
  let userPrompt = `SOURCE DOCUMENT:
${noteContent}

USER ANSWERS:
`;
  qnaPairs.forEach((pair, index) => {
    let maxMarks = 1;
    const marksMatch = pair.question.match(/\((\d)\)\s*$/);
    if (marksMatch && [1, 2, 3].includes(parseInt(marksMatch[1], 10))) {
      maxMarks = parseInt(marksMatch[1], 10);
    } else if (pair.type === "long") {
      maxMarks = 2;
    } else if (pair.type === "extended") {
      maxMarks = 3;
    }
    userPrompt += `Q${index + 1} (maxMarks=${maxMarks}): ${pair.question}
Answer: ${pair.answer || "[No answer provided]"}

`;
  });
  userPrompt += `Please return a JSON array of objects, each with { "questionNumber", "marks", "maxMarks", "feedback" }. 
Marks should reflect the quality of the answer (0 = no credit, maxMarks = full credit, with partial marks possible).
No extra fields, no markdown code blocks.`;
  try {
    let responseData;
    switch (provider) {
      case "openai":
        responseData = await callOpenAI(systemMessage, userPrompt, apiKey, model, 1e3);
        break;
      case "anthropic":
        responseData = await callAnthropic(systemMessage, userPrompt, apiKey, model, 1e3);
        break;
      case "deepseek":
        responseData = await callDeepSeek(systemMessage, userPrompt, apiKey, model, 1e3);
        break;
      case "gemini":
        responseData = await callGemini(systemMessage, userPrompt, apiKey, model, 1e3);
        break;
      case "mistral":
        responseData = await callMistral(systemMessage, userPrompt, apiKey, model, 1e3);
        break;
      case "ollama":
        const ollamaUrl = (ollamaSettings == null ? void 0 : ollamaSettings.url) || "http://localhost:11434";
        responseData = await callOllama(systemMessage, userPrompt, model, 1e3, ollamaUrl);
        break;
      default:
        throw new Error(`Unsupported provider: ${provider}`);
    }
    return parseMarkingResponse(responseData);
  } catch (error) {
    if (error instanceof ContextLengthExceededError) {
      throw error;
    }
    if (error instanceof Error && (error.message.includes("context_length_exceeded") || error.message.includes("maximum context length"))) {
      throw new ContextLengthExceededError(
        "The document is too large for the model's context window. Please split your document into smaller sections."
      );
    }
    throw error;
  }
}
function getDefaultModel(provider) {
  switch (provider) {
    case "openai":
      return "gpt-4";
    case "anthropic":
      return "claude-3-opus-20240229";
    case "deepseek":
      return "deepseek-chat";
    case "gemini":
      return "gemini-pro";
    case "mistral":
      return "mistral-medium";
    case "ollama":
      return "llama3";
    default:
      return "";
  }
}
function parseTestQuestionsResponse(rawContent) {
  if (!rawContent) {
    throw new Error("No content from LLM for test questions.");
  }
  let jsonString = rawContent.trim();
  if (jsonString.startsWith("```json")) {
    jsonString = jsonString.slice(7).trim();
  }
  if (jsonString.endsWith("```")) {
    jsonString = jsonString.slice(0, -3).trim();
  }
  const lastBrace = jsonString.lastIndexOf("}");
  if (lastBrace !== -1) {
    jsonString = jsonString.slice(0, lastBrace + 1);
  }
  if (!jsonString.endsWith("}")) {
    jsonString += "}";
  }
  try {
    const parsed = JSON.parse(jsonString);
    return parsed;
  } catch (err) {
    throw new Error("Failed to parse JSON response for test questions");
  }
}
function parseMarkingResponse(feedback) {
  if (!feedback) {
    throw new Error("No marking feedback returned by LLM.");
  }
  feedback = feedback.trim();
  if (feedback.startsWith("```")) {
    feedback = feedback.replace(/^```[a-z]*\n?/, "").replace(/```$/, "").trim();
  }
  try {
    return JSON.parse(feedback);
  } catch (err) {
    throw new Error("Failed to parse LLM marking JSON output.");
  }
}
async function callOpenAI(systemMessage, userPrompt, apiKey, model = "gpt-4", maxTokens = 500) {
  var _a, _b, _c, _d, _e;
  const requestBody = {
    model,
    messages: [
      { role: "system", content: systemMessage },
      { role: "user", content: userPrompt }
    ],
    temperature: 0.7,
    max_tokens: maxTokens
  };
  const response = await fetch(OPENAI_API_URL, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${apiKey}`,
      "Content-Type": "application/json"
    },
    body: JSON.stringify(requestBody)
  });
  if (!response.ok) {
    const errorData = await response.json();
    if (((_a = errorData.error) == null ? void 0 : _a.code) === "context_length_exceeded") {
      throw new ContextLengthExceededError(
        `The document is too large for ${model}'s context window. Please split your document into smaller sections.`
      );
    }
    throw new Error(`OpenAI API Error: ${response.status} - ${((_b = errorData.error) == null ? void 0 : _b.message) || response.statusText}`);
  }
  const responseData = await response.json();
  return ((_e = (_d = (_c = responseData.choices) == null ? void 0 : _c[0]) == null ? void 0 : _d.message) == null ? void 0 : _e.content) || "";
}
async function callAnthropic(systemMessage, userPrompt, apiKey, model = "claude-3-opus-20240229", maxTokens = 500) {
  var _a, _b, _c, _d, _e, _f;
  const requestBody = {
    model,
    messages: [
      {
        role: "user",
        content: [
          {
            type: "text",
            text: `${systemMessage}

${userPrompt}`
          }
        ]
      }
    ],
    max_tokens: maxTokens
  };
  const response = await fetch(ANTHROPIC_API_URL, {
    method: "POST",
    headers: {
      "x-api-key": apiKey,
      "anthropic-version": "2023-06-01",
      "Content-Type": "application/json"
    },
    body: JSON.stringify(requestBody)
  });
  if (!response.ok) {
    const errorData = await response.json();
    if (((_a = errorData.error) == null ? void 0 : _a.type) === "context_length_exceeded" || ((_c = (_b = errorData.error) == null ? void 0 : _b.message) == null ? void 0 : _c.includes("context window"))) {
      throw new ContextLengthExceededError(
        `The document is too large for ${model}'s context window. Please split your document into smaller sections.`
      );
    }
    throw new Error(`Anthropic API Error: ${response.status} - ${((_d = errorData.error) == null ? void 0 : _d.message) || response.statusText}`);
  }
  const responseData = await response.json();
  return ((_f = (_e = responseData.content) == null ? void 0 : _e[0]) == null ? void 0 : _f.text) || "";
}
async function callDeepSeek(systemMessage, userPrompt, apiKey, model = "deepseek-chat", maxTokens = 500) {
  var _a, _b, _c, _d, _e, _f, _g;
  const requestBody = {
    model,
    messages: [
      { role: "system", content: systemMessage },
      { role: "user", content: userPrompt }
    ],
    max_tokens: maxTokens
  };
  const response = await fetch(DEEPSEEK_API_URL, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${apiKey}`,
      "Content-Type": "application/json"
    },
    body: JSON.stringify(requestBody)
  });
  if (!response.ok) {
    const errorData = await response.json();
    if (((_a = errorData.error) == null ? void 0 : _a.code) === "context_window_exceeded" || ((_c = (_b = errorData.error) == null ? void 0 : _b.message) == null ? void 0 : _c.includes("context length"))) {
      throw new ContextLengthExceededError(
        `The document is too large for ${model}'s context window. Please split your document into smaller sections.`
      );
    }
    throw new Error(`DeepSeek API Error: ${response.status} - ${((_d = errorData.error) == null ? void 0 : _d.message) || response.statusText}`);
  }
  const responseData = await response.json();
  return ((_g = (_f = (_e = responseData.choices) == null ? void 0 : _e[0]) == null ? void 0 : _f.message) == null ? void 0 : _g.content) || "";
}
async function callGemini(systemMessage, userPrompt, apiKey, model = "gemini-pro", maxTokens = 500) {
  var _a, _b, _c, _d, _e, _f, _g, _h, _i, _j;
  const fullPrompt = `${systemMessage}

${userPrompt}`;
  const modelEndpoint = model === "gemini-pro" ? "gemini-pro" : model;
  const apiUrl = `https://generativelanguage.googleapis.com/v1beta/models/${modelEndpoint}:generateContent?key=${apiKey}`;
  const requestBody = {
    contents: [
      {
        parts: [
          { text: fullPrompt }
        ]
      }
    ],
    generationConfig: {
      maxOutputTokens: maxTokens,
      temperature: 0.7
    }
  };
  const response = await fetch(apiUrl, {
    method: "POST",
    headers: {
      "Content-Type": "application/json"
    },
    body: JSON.stringify(requestBody)
  });
  if (!response.ok) {
    const errorData = await response.json();
    if (((_b = (_a = errorData.error) == null ? void 0 : _a.message) == null ? void 0 : _b.includes("context length")) || ((_d = (_c = errorData.error) == null ? void 0 : _c.message) == null ? void 0 : _d.includes("token limit"))) {
      throw new ContextLengthExceededError(
        `The document is too large for ${model}'s context window. Please split your document into smaller sections.`
      );
    }
    throw new Error(`Google Gemini API Error: ${response.status} - ${((_e = errorData.error) == null ? void 0 : _e.message) || response.statusText}`);
  }
  const responseData = await response.json();
  return ((_j = (_i = (_h = (_g = (_f = responseData.candidates) == null ? void 0 : _f[0]) == null ? void 0 : _g.content) == null ? void 0 : _h.parts) == null ? void 0 : _i[0]) == null ? void 0 : _j.text) || "";
}
async function callMistral(systemMessage, userPrompt, apiKey, model = "mistral-medium", maxTokens = 500) {
  var _a, _b, _c, _d, _e, _f, _g, _h, _i;
  const requestBody = {
    model,
    messages: [
      { role: "system", content: systemMessage },
      { role: "user", content: userPrompt }
    ],
    temperature: 0.7,
    max_tokens: maxTokens
  };
  const response = await fetch(MISTRAL_API_URL, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${apiKey}`,
      "Content-Type": "application/json"
    },
    body: JSON.stringify(requestBody)
  });
  if (!response.ok) {
    const errorData = await response.json();
    if (((_a = errorData.error) == null ? void 0 : _a.type) === "context_length_exceeded" || ((_c = (_b = errorData.error) == null ? void 0 : _b.message) == null ? void 0 : _c.includes("context")) || ((_e = (_d = errorData.error) == null ? void 0 : _d.message) == null ? void 0 : _e.includes("token limit"))) {
      throw new ContextLengthExceededError(
        `The document is too large for ${model}'s context window. Please split your document into smaller sections.`
      );
    }
    throw new Error(`Mistral API Error: ${response.status} - ${((_f = errorData.error) == null ? void 0 : _f.message) || response.statusText}`);
  }
  const responseData = await response.json();
  return ((_i = (_h = (_g = responseData.choices) == null ? void 0 : _g[0]) == null ? void 0 : _h.message) == null ? void 0 : _i.content) || "";
}
async function callOllama(systemMessage, userPrompt, model = "llama3", maxTokens = 500, ollamaUrl = "http://localhost:11434") {
  var _a;
  const fullPrompt = `${systemMessage}

${userPrompt}`;
  const generateUrl = `${ollamaUrl}/api/generate`;
  const requestBody = {
    model,
    prompt: fullPrompt,
    stream: false,
    options: {
      num_predict: maxTokens
    }
  };
  try {
    const response = await fetch(generateUrl, {
      method: "POST",
      headers: {
        "Content-Type": "application/json"
      },
      body: JSON.stringify(requestBody)
    });
    if (!response.ok) {
      const errorText = await response.text();
      let errorData = {};
      try {
        errorData = JSON.parse(errorText);
      } catch (e) {
      }
      if (errorText.includes("context window") || errorText.includes("context length")) {
        throw new ContextLengthExceededError(
          `The document is too large for ${model}'s context window. Please split your document into smaller sections.`
        );
      }
      throw new Error(`Ollama API Error: ${response.status} - ${errorData.error || errorText || response.statusText}`);
    }
    const responseData = await response.json();
    return responseData.response || "";
  } catch (error) {
    if (error instanceof ContextLengthExceededError) {
      throw error;
    }
    if ((_a = error.message) == null ? void 0 : _a.includes("Failed to fetch")) {
      throw new Error(`Could not connect to Ollama server at ${ollamaUrl}. Is it running?`);
    }
    throw error;
  }
}

// src/ui/DashboardView.ts
var VIEW_TYPE = "rag-test-view";
var TestDashboardView = class extends import_obsidian.ItemView {
  constructor(leaf, app, pluginData, plugin) {
    super(leaf);
    this.isRefreshing = false;
    this.fileTreeRoot = { name: "root", path: "", isFolder: true, children: [] };
    this.expandedFolders = /* @__PURE__ */ new Set();
    this.pluginData = pluginData;
    this.plugin = plugin;
    this.buildFileTree();
  }
  getViewType() {
    return VIEW_TYPE;
  }
  getDisplayText() {
    return "Test dashboard";
  }
  async onOpen() {
    if (!this.pluginData || this.pluginData.length === 0) {
      this.handleRefresh();
    } else {
      this.render();
    }
  }
  /**
   * Creates a refresh icon using Obsidian's createEl
   */
  createRefreshIcon(element) {
    const svgContainer = element.createEl("span", { cls: "icon-container" });
    (0, import_obsidian.setIcon)(svgContainer, "refresh-cw");
    element.createEl("span", { text: "Refresh" });
  }
  /**
   * Creates a folder toggle icon
   */
  createFolderToggleIcon(element, expanded) {
    (0, import_obsidian.setIcon)(element, expanded ? "chevron-down" : "chevron-right");
  }
  /**
   * Creates a folder icon
   */
  createFolderIcon(element) {
    (0, import_obsidian.setIcon)(element, "folder");
  }
  /**
   * Creates a file icon
   */
  createFileIcon(element) {
    (0, import_obsidian.setIcon)(element, "file-text");
  }
  /**
   * Creates a file with lines icon
   */
  createFileWithLinesIcon(element) {
    (0, import_obsidian.setIcon)(element, "file-text");
  }
  /**
   * Creates a badge with icon and text
   */
  createBadge(element, text, colorClass = "none") {
    const badge = element.createEl("div", { cls: `status-badge ${colorClass}` });
    const iconContainer = badge.createEl("span", { cls: "badge-icon" });
    this.createFileIcon(iconContainer);
    badge.createEl("span", { text });
  }
  createProgressRing(element, percent, color) {
    const svg = document.createElementNS("http://www.w3.org/2000/svg", "svg");
    svg.setAttribute("class", "progress-ring");
    svg.setAttribute("width", "18");
    svg.setAttribute("height", "18");
    svg.setAttribute("viewBox", "0 0 24 24");
    const radius = 8;
    const circumference = 2 * Math.PI * radius;
    const dashoffset = circumference * (1 - percent / 100);
    const circle1 = document.createElementNS("http://www.w3.org/2000/svg", "circle");
    circle1.setAttribute("class", "progress-ring-circle");
    circle1.setAttribute("cx", "12");
    circle1.setAttribute("cy", "12");
    circle1.setAttribute("r", radius.toString());
    const circle2 = document.createElementNS("http://www.w3.org/2000/svg", "circle");
    circle2.setAttribute("class", "progress-ring-progress");
    circle2.setAttribute("cx", "12");
    circle2.setAttribute("cy", "12");
    circle2.setAttribute("r", radius.toString());
    circle2.setAttribute("stroke", color);
    circle2.setAttribute("stroke-dasharray", `${circumference} ${circumference}`);
    circle2.setAttribute("stroke-dashoffset", dashoffset.toString());
    svg.appendChild(circle1);
    svg.appendChild(circle2);
    element.appendChild(svg);
    element.createEl("span", {
      text: `${Math.round(percent)}%`
    });
  }
  createProgressCount(element, current, total, color) {
    const svg = document.createElementNS("http://www.w3.org/2000/svg", "svg");
    svg.setAttribute("class", "progress-ring");
    svg.setAttribute("width", "18");
    svg.setAttribute("height", "18");
    svg.setAttribute("viewBox", "0 0 24 24");
    const radius = 8;
    const circumference = 2 * Math.PI * radius;
    const percent = current / total * 100;
    const dashoffset = circumference * (1 - percent / 100);
    const circle1 = document.createElementNS("http://www.w3.org/2000/svg", "circle");
    circle1.setAttribute("class", "progress-ring-circle");
    circle1.setAttribute("cx", "12");
    circle1.setAttribute("cy", "12");
    circle1.setAttribute("r", radius.toString());
    const circle2 = document.createElementNS("http://www.w3.org/2000/svg", "circle");
    circle2.setAttribute("class", "progress-ring-progress");
    circle2.setAttribute("cx", "12");
    circle2.setAttribute("cy", "12");
    circle2.setAttribute("r", radius.toString());
    circle2.setAttribute("stroke", color);
    circle2.setAttribute("stroke-dasharray", `${circumference} ${circumference}`);
    circle2.setAttribute("stroke-dashoffset", dashoffset.toString());
    svg.appendChild(circle1);
    svg.appendChild(circle2);
    element.appendChild(svg);
    element.createEl("span", {
      text: `${current}/${total}`
    });
  }
  createSpinner(element) {
    element.createDiv({ cls: "spinner" });
  }
  showFullPageSpinner(loadingText) {
    const container = this.containerEl;
    const loadingOverlay = container.createDiv({ cls: "full-page-overlay" });
    const spinnerContainer = loadingOverlay.createDiv({ cls: "loading-container" });
    this.createSpinner(spinnerContainer);
    spinnerContainer.createEl("p", { text: loadingText, cls: "loading-text" });
    return loadingOverlay;
  }
  hideFullPageSpinner(overlay) {
    if (overlay) {
      overlay.remove();
    }
  }
  async cleanupStaleTestDocuments() {
    const ragPlugin = this.plugin;
    if (!ragPlugin) {
      return 0;
    }
    const validFilePaths = new Set(ragPlugin.indexedNotes.map((note) => note.filePath));
    const staleTestPaths = [];
    Object.keys(ragPlugin.testDocuments).forEach((path) => {
      if (!validFilePaths.has(path)) {
        staleTestPaths.push(path);
      }
    });
    if (staleTestPaths.length > 0) {
      staleTestPaths.forEach((path) => {
        delete ragPlugin.testDocuments[path];
      });
      await ragPlugin.saveSettings();
    }
    return staleTestPaths.length;
  }
  async onClose() {
  }
  buildFileTree() {
    this.fileTreeRoot = { name: "root", path: "", isFolder: true, children: [] };
    this.pluginData.forEach((note) => {
      const pathParts = note.filePath.split("/");
      let currentNode = this.fileTreeRoot;
      let currentPath = "";
      for (let i = 0; i < pathParts.length - 1; i++) {
        const folderName = pathParts[i];
        currentPath = currentPath ? `${currentPath}/${folderName}` : folderName;
        let folderNode = currentNode.children.find(
          (child) => child.isFolder && child.name === folderName
        );
        if (!folderNode) {
          folderNode = {
            name: folderName,
            path: currentPath,
            isFolder: true,
            children: [],
            expanded: this.expandedFolders.has(currentPath)
          };
          currentNode.children.push(folderNode);
        }
        currentNode = folderNode;
      }
      const fileName = pathParts[pathParts.length - 1];
      currentNode.children.push({
        name: fileName,
        path: note.filePath,
        isFolder: false,
        children: [],
        note
      });
    });
    this.sortFileTree(this.fileTreeRoot);
  }
  sortFileTree(node) {
    node.children.sort((a, b) => {
      if (a.isFolder && !b.isFolder)
        return -1;
      if (!a.isFolder && b.isFolder)
        return 1;
      return a.name.localeCompare(b.name);
    });
    node.children.forEach((child) => {
      if (child.isFolder) {
        this.sortFileTree(child);
      }
    });
  }
  async render() {
    const container = this.containerEl;
    container.empty();
    container.addClass("test-dashboard-container");
    const ragPlugin = this.plugin;
    if (!ragPlugin) {
      container.createEl("div", {
        cls: "empty-state",
        text: "Test plugin not found."
      });
      return;
    }
    const header = container.createEl("div", { cls: "dashboard-header" });
    header.createEl("h2", {
      text: "Test dashboard",
      cls: "dashboard-title"
    });
    const buttonContainer = header.createEl("div", { cls: "dashboard-actions" });
    const refreshBtn = buttonContainer.createEl("button", {
      cls: "dashboard-button secondary",
      attr: {
        title: "Refresh file index"
      }
    });
    if (this.isRefreshing) {
      this.createSpinner(refreshBtn);
      refreshBtn.createSpan({ text: " Refreshing..." });
    } else {
      this.createRefreshIcon(refreshBtn);
    }
    refreshBtn.disabled = this.isRefreshing;
    refreshBtn.onclick = () => this.handleRefresh();
    const createBtn = buttonContainer.createEl("button", {
      text: "Create tests",
      cls: "dashboard-button primary"
    });
    createBtn.disabled = true;
    createBtn.onclick = () => this.createTests();
    const fileTreeContainer = container.createEl("div", { cls: "file-tree-container" });
    if (!this.pluginData || this.pluginData.length === 0) {
      fileTreeContainer.createEl("div", {
        cls: "empty-state",
        text: "No files found. Click Refresh to scan your vault."
      });
      return;
    }
    this.buildFileTree();
    this.renderFileTree(fileTreeContainer, this.fileTreeRoot, createBtn);
    this.updateCreateBtn(createBtn);
    const markAllContainer = container.createEl("div", {
      cls: "mark-all-container"
    });
    const markAllBtn = markAllContainer.createEl("button", {
      cls: "dashboard-button primary mark-all-button",
      text: "Mark all tests"
    });
    const hasPartialTests = Object.entries(this.plugin.testDocuments).some(([path, doc]) => {
      return doc.answers && Object.values(doc.answers).some((answer) => answer && answer.trim().length > 0) && typeof doc.score !== "number";
    });
    markAllBtn.disabled = !hasPartialTests;
    markAllBtn.onclick = () => this.markAllTests();
  }
  renderFileTree(container, node, createBtn, level = 0) {
    if (node === this.fileTreeRoot) {
      const treeRoot = container.createEl("div", { cls: "file-tree" });
      node.children.forEach((child) => {
        this.renderFileTree(treeRoot, child, createBtn, level);
      });
      return;
    }
    const item = container.createEl("div", { cls: "file-tree-item" });
    if (level <= 12) {
      item.addClass(`tree-item-padding-level-${level}`);
    } else {
      item.addClass("tree-item-padding-level-max");
    }
    if (node.isFolder) {
      const folderRow = item.createEl("div", { cls: "folder-row" });
      const toggleBtn = folderRow.createEl("div", {
        cls: `folder-toggle ${node.expanded ? "expanded" : "collapsed"}`
      });
      this.createFolderToggleIcon(toggleBtn, node.expanded || false);
      const folderIcon = folderRow.createEl("span", { cls: "folder-icon" });
      this.createFolderIcon(folderIcon);
      folderRow.createEl("span", { text: node.name, cls: "folder-name" });
      folderRow.onclick = (e) => {
        node.expanded = !node.expanded;
        if (node.expanded) {
          this.expandedFolders.add(node.path);
        } else {
          this.expandedFolders.delete(node.path);
        }
        this.render();
        e.stopPropagation();
      };
      if (node.expanded) {
        const childContainer = item.createEl("div", { cls: "folder-children" });
        node.children.forEach((child) => {
          this.renderFileTree(childContainer, child, createBtn, level + 1);
        });
      }
    } else {
      const fileRow = item.createEl("div", { cls: "file-row" });
      const checkbox = fileRow.createEl("input", {
        type: "checkbox",
        cls: "file-checkbox"
      });
      checkbox.dataset.filePath = node.path;
      const fileIcon = fileRow.createEl("span", { cls: "file-icon" });
      this.createFileIcon(fileIcon);
      fileRow.createEl("span", { text: node.name, cls: "file-name" });
      const docState = this.plugin.testDocuments[node.path];
      const statusSpan = fileRow.createEl("span", { cls: "status-icon" });
      if (!docState) {
        this.createBadge(statusSpan, "No Tests", "none");
      } else if (typeof docState.score === "number") {
        const score = docState.score;
        const colorClass = score >= 80 ? "complete" : "partial";
        const button = statusSpan.createEl("button", {
          attr: { title: "Open test document" }
        });
        const badge = button.createEl("div", { cls: `status-badge ${colorClass}` });
        this.createProgressRing(badge, Math.round(score), score >= 80 ? "#22c55e" : "#f59e0b");
        button.onclick = (e) => {
          this.plugin.openQuestionDoc(node.path);
          e.stopPropagation();
        };
      } else {
        const totalQ = docState.questions.length;
        const answeredCount = Object.values(docState.answers || {}).filter((val) => val.trim()).length;
        const colorClass = answeredCount === 0 ? "none" : answeredCount === totalQ ? "complete" : "in-progress";
        const button = statusSpan.createEl("button", {
          attr: { title: "Open test document" }
        });
        const badge = button.createEl("div", { cls: `status-badge ${colorClass}` });
        if (answeredCount === 0) {
          const iconContainer = badge.createEl("span", { cls: "badge-icon" });
          this.createFileWithLinesIcon(iconContainer);
          badge.createEl("span", { text: "Start" });
        } else {
          this.createProgressCount(badge, answeredCount, totalQ, "#f59e0b");
        }
        button.onclick = (e) => {
          this.plugin.openQuestionDoc(node.path);
          e.stopPropagation();
        };
      }
      checkbox.onchange = () => this.updateCreateBtn(createBtn);
    }
  }
  updateCreateBtn(btn) {
    const boxes = this.containerEl.querySelectorAll('input[type="checkbox"]');
    btn.disabled = !Array.from(boxes).some((b) => b.checked);
  }
  async handleRefresh() {
    if (this.isRefreshing)
      return;
    try {
      this.isRefreshing = true;
      this.render();
      new import_obsidian.Notice("\u{1F504} Refreshing test index...");
      const refreshedNotes = await this.plugin.indexTestNotes();
      this.pluginData = refreshedNotes;
      const removedCount = await this.cleanupStaleTestDocuments();
      this.render();
      if (removedCount > 0) {
        new import_obsidian.Notice(`\u2705 Indexed ${refreshedNotes.length} notes and removed ${removedCount} stale test documents.`);
      } else {
        new import_obsidian.Notice(`\u2705 Indexed ${refreshedNotes.length} notes.`);
      }
    } catch (error) {
      console.error("Error refreshing index:", error);
      new import_obsidian.Notice("\u274C Error refreshing index. Check console for details.");
    } finally {
      this.isRefreshing = false;
      this.render();
    }
  }
  async createTests() {
    const ragPlugin = this.plugin;
    if (!ragPlugin) {
      new import_obsidian.Notice("\u274C Test Plugin not found.");
      return;
    }
    const provider = ragPlugin.settings.llmProvider;
    const apiKey = ragPlugin.settings.apiKeys[provider];
    if (provider !== "ollama" && !apiKey) {
      new import_obsidian.Notice(`\u274C ${this.getProviderDisplayName(provider)} API Key is missing! Please set it in the plugin settings.`);
      return;
    }
    const boxes = this.containerEl.querySelectorAll('input[type="checkbox"]');
    const tasks = [];
    await this.cleanupStaleTestDocuments();
    for (const box of Array.from(boxes)) {
      const input = box;
      if (input.checked) {
        const filePath = input.dataset.filePath;
        if (!filePath)
          continue;
        const note = this.pluginData.find((n) => n.filePath === filePath);
        if (!note)
          continue;
        const fileRow = input.closest(".file-row");
        const icon = fileRow == null ? void 0 : fileRow.querySelector(".status-icon");
        if (icon) {
          icon.empty();
          this.createSpinner(icon);
        }
        tasks.push((async () => {
          var _a;
          try {
            const res = await generateTestQuestions(
              [note],
              ragPlugin.settings.llmProvider,
              ragPlugin.settings.apiKeys,
              ragPlugin.settings.models,
              ragPlugin.settings.ollamaSettings
            );
            ragPlugin.testDocuments[filePath] = {
              description: res.description,
              questions: res.questions,
              answers: {}
            };
            await ragPlugin.saveSettings();
            if (icon) {
              icon.empty();
              const button = icon.createEl("button", {
                attr: { title: "Open test document" }
              });
              const badge = button.createEl("div", { cls: "status-badge none" });
              const iconContainer = badge.createEl("span", { cls: "badge-icon" });
              this.createFileWithLinesIcon(iconContainer);
              badge.createEl("span", { text: "Start" });
              button.onclick = (e) => {
                ragPlugin.openQuestionDoc(filePath);
                e.stopPropagation();
              };
            }
          } catch (error) {
            console.error("Error generating tests:", error);
            if (icon) {
              icon.empty();
              this.createBadge(icon, "No Tests", "none");
            }
            if (error instanceof ContextLengthExceededError) {
              new import_obsidian.Notice(`\u274C ${filePath}: ${error.message}`, 1e4);
            } else if ((_a = error.message) == null ? void 0 : _a.includes("Failed to parse JSON")) {
              const modelName = ragPlugin.settings.models[ragPlugin.settings.llmProvider];
              new import_obsidian.Notice(`\u274C ${filePath}: Model "${modelName}" failed to generate proper JSON. Please try a more capable model.`, 1e4);
            } else {
              new import_obsidian.Notice(`\u274C Error generating tests for ${filePath}: ${error.message}`, 5e3);
            }
          }
        })());
      }
    }
    try {
      await Promise.all(tasks);
      new import_obsidian.Notice("\u2705 Test generation complete!");
      boxes.forEach((box) => {
        box.checked = false;
      });
      const createBtn = this.containerEl.querySelector(".dashboard-button.primary");
      if (createBtn) {
        createBtn.disabled = true;
      }
    } catch (error) {
      console.error("Error in test generation:", error);
      new import_obsidian.Notice("\u274C Some tests could not be generated. Check console for details.");
    }
  }
  getProviderDisplayName(provider) {
    switch (provider) {
      case "openai":
        return "OpenAI";
      case "anthropic":
        return "Claude";
      case "deepseek":
        return "DeepSeek";
      case "gemini":
        return "Gemini";
      case "mistral":
        return "Mistral";
      case "ollama":
        return "Ollama";
      default:
        return provider.charAt(0).toUpperCase() + provider.slice(1);
    }
  }
  async markAllTests() {
    const ragPlugin = this.plugin;
    if (!ragPlugin) {
      new import_obsidian.Notice("\u274C Test Plugin not found.");
      return;
    }
    const provider = ragPlugin.settings.llmProvider;
    const apiKeys = ragPlugin.settings.apiKeys;
    if (provider !== "ollama" && !apiKeys[provider]) {
      new import_obsidian.Notice(`\u274C ${this.getProviderDisplayName(provider)} API Key is missing! Please set it in the plugin settings.`);
      return;
    }
    await this.cleanupStaleTestDocuments();
    const testsToMark = [];
    const testsAlreadyMarked = [];
    Object.entries(ragPlugin.testDocuments).forEach(([path, doc]) => {
      if (doc.answers) {
        const hasActualAnswers = Object.values(doc.answers).some(
          (answer) => answer && answer.trim().length > 0
        );
        if (hasActualAnswers) {
          if (typeof doc.score === "number") {
            testsAlreadyMarked.push(path);
          } else {
            testsToMark.push(path);
          }
        }
      }
    });
    if (testsToMark.length === 0) {
      if (testsAlreadyMarked.length > 0) {
        new import_obsidian.Notice(`\u2705 All tests with answers (${testsAlreadyMarked.length}) are already marked.`);
      } else {
        new import_obsidian.Notice("No tests with answers to mark.");
      }
      return;
    }
    const validTestsToMark = [];
    const missingFromIndex = [];
    for (const filePath of testsToMark) {
      const indexedNote = ragPlugin.indexedNotes.find((n) => n.filePath === filePath);
      if (indexedNote) {
        validTestsToMark.push(filePath);
      } else {
        missingFromIndex.push(filePath);
      }
    }
    if (missingFromIndex.length > 0) {
      new import_obsidian.Notice("There's an issue with the test index. Please restart Obsidian and try again.", 8e3);
      return;
    }
    if (validTestsToMark.length === 0) {
      if (testsAlreadyMarked.length > 0) {
        new import_obsidian.Notice(`\u2705 All valid tests (${testsAlreadyMarked.length}) are already marked.`);
      } else {
        new import_obsidian.Notice("No valid tests with answers found.");
      }
      return;
    }
    const container = this.containerEl;
    const loadingOverlay = container.createDiv({ cls: "full-page-overlay" });
    const spinnerContainer = loadingOverlay.createDiv({ cls: "loading-container" });
    this.createSpinner(spinnerContainer);
    spinnerContainer.createEl("p", {
      text: `Marking ${validTestsToMark.length} tests using ${this.getProviderDisplayName(provider)}... This may take a few moments.`,
      cls: "loading-text"
    });
    try {
      const markingPromises = validTestsToMark.map(async (filePath) => {
        try {
          const indexedNote = ragPlugin.indexedNotes.find((n) => n.filePath === filePath);
          if (!indexedNote) {
            return { filePath, success: false, error: "Note content not found" };
          }
          const docState = ragPlugin.testDocuments[filePath];
          const noteContent = indexedNote.content;
          const qnaPairs = docState.questions.map((test, idx) => ({
            question: test.question,
            answer: docState.answers[idx] || "",
            type: test.type
          }));
          if (!qnaPairs.some((pair) => pair.answer.trim())) {
            return { filePath, success: false, error: "No answers to mark" };
          }
          const feedbackArray = await markTestAnswers(
            noteContent,
            qnaPairs,
            provider,
            apiKeys,
            this.plugin.settings.models,
            this.plugin.settings.ollamaSettings
          );
          let totalPossibleMarks = 0;
          let totalEarnedMarks = 0;
          const markResults = new Array(docState.questions.length).fill(null);
          feedbackArray.forEach((item) => {
            const i = item.questionNumber - 1;
            if (i >= 0 && i < docState.questions.length) {
              markResults[i] = {
                marks: item.marks,
                maxMarks: item.maxMarks,
                feedback: item.feedback
              };
              totalPossibleMarks += item.maxMarks;
              totalEarnedMarks += item.marks;
            }
          });
          const percentage = totalPossibleMarks ? totalEarnedMarks / totalPossibleMarks * 100 : 0;
          ragPlugin.testDocuments[filePath] = {
            ...ragPlugin.testDocuments[filePath],
            score: percentage,
            markResults
          };
          return {
            filePath,
            success: true,
            score: percentage,
            earnedMarks: totalEarnedMarks,
            possibleMarks: totalPossibleMarks
          };
        } catch (error) {
          console.error(`Error marking test ${filePath}:`, error);
          return { filePath, success: false, error: error.message || "Unknown error" };
        }
      });
      const results = await Promise.all(markingPromises);
      await ragPlugin.saveSettings();
      this.render();
      const successful = results.filter((r) => r.success).length;
      const failed = results.length - successful;
      if (failed > 0) {
        new import_obsidian.Notice(`\u2705 Marked ${successful} tests successfully. \u274C ${failed} tests failed.`);
      } else {
        new import_obsidian.Notice(`\u2705 Successfully marked all ${successful} tests with ${this.getProviderDisplayName(provider)}!`);
      }
    } catch (error) {
      console.error("Error in markAllTests:", error);
      new import_obsidian.Notice(`\u274C Error marking tests with ${this.getProviderDisplayName(provider)}. Check console for details.`);
    } finally {
      if (loadingOverlay) {
        loadingOverlay.remove();
      }
    }
  }
};

// src/ui/QuestionView.ts
var import_obsidian2 = require("obsidian");
var QUESTION_VIEW_TYPE = "question-document-view";
var QuestionDocumentView = class extends import_obsidian2.ItemView {
  constructor(leaf, app, plugin, state) {
    super(leaf);
    this.generatedTests = [];
    this.answers = {};
    this.markResults = [];
    this.scoreSummary = "";
    this.textareaElements = [];
    this.app = app;
    this.plugin = plugin;
    this.description = state.description;
    this.generatedTests = state.questions;
    this.filePath = "";
  }
  getViewType() {
    return QUESTION_VIEW_TYPE;
  }
  getDisplayText() {
    return this.filePath ? `Test: ${this.filePath}` : "Generated test questions";
  }
  async onOpen() {
    this.render();
  }
  async onClose() {
  }
  showSpinner() {
    var _a;
    const container = this.containerEl;
    const spinnerOverlay = container.createDiv({ cls: "spinner-overlay" });
    const contentHeight = Math.max(
      container.scrollHeight,
      ((_a = container.querySelector(".test-document-container")) == null ? void 0 : _a.scrollHeight) || 0
    );
    spinnerOverlay.style.height = `${contentHeight}px`;
    const spinnerFixed = spinnerOverlay.createDiv({ cls: "spinner-fixed-center" });
    spinnerFixed.createDiv({ cls: "spinner" });
    spinnerFixed.createEl("p", {
      text: "Marking in progress...",
      cls: "loading-text"
    });
    return spinnerOverlay;
  }
  hideSpinner(spinnerOverlay) {
    if (spinnerOverlay) {
      spinnerOverlay.detach();
    }
  }
  adjustTextareaHeight(textarea) {
    textarea.addClass("textarea-height-auto");
    const scrollHeight = textarea.scrollHeight;
    textarea.removeClass("textarea-height-auto");
    textarea.setAttribute("data-height", scrollHeight + "px");
    textarea.addClass("textarea-expanded");
    textarea.style.setProperty("--textarea-height", scrollHeight + "px");
  }
  setupAutoResizeTextarea(textarea) {
    this.textareaElements.push(textarea);
    textarea.addClass("auto-height-textarea");
    this.adjustTextareaHeight(textarea);
    textarea.addEventListener("input", () => {
      this.adjustTextareaHeight(textarea);
    });
  }
  render() {
    var _a;
    const container = this.containerEl;
    container.empty();
    this.textareaElements = [];
    container.addClass("test-document-container");
    container.addClass("test-container-relative");
    if (!((_a = this.generatedTests) == null ? void 0 : _a.length)) {
      container.createEl("p", { text: "No test questions available." });
      return;
    }
    container.createEl("p", {
      text: this.description,
      cls: "test-description"
    });
    const formEl = container.createEl("form");
    formEl.addClass("overflow-visible");
    this.generatedTests.forEach((test, index) => {
      const questionDiv = formEl.createEl("div", { cls: "question-item" });
      const label = questionDiv.createEl("label", { cls: "question-label" });
      label.createSpan({ cls: "question-number", text: `${index + 1}` });
      label.createSpan({ text: test.question });
      const textarea = questionDiv.createEl("textarea", {
        cls: "answer-input",
        attr: {
          placeholder: "Type your answer here",
          rows: "3"
        }
      });
      if (this.answers[index]) {
        textarea.value = this.answers[index];
      }
      const result = this.markResults[index];
      if (result) {
        const scorePercentage = result.marks / result.maxMarks * 100;
        if (scorePercentage >= 80) {
          textarea.addClass("correct");
        } else if (scorePercentage > 0) {
          textarea.addClass("partial");
        } else {
          textarea.addClass("incorrect");
        }
      }
      this.setupAutoResizeTextarea(textarea);
      textarea.addEventListener("input", () => {
        this.answers[index] = textarea.value;
        this.saveAnswers();
      });
      const feedbackEl = questionDiv.createEl("div", { cls: "feedback" });
      if (result) {
        feedbackEl.createEl("div", {
          cls: "marks-display",
          text: `${result.marks}/${result.maxMarks} marks`
        });
        const scorePercentage = result.marks / result.maxMarks * 100;
        if (scorePercentage >= 80) {
          feedbackEl.addClass("correct");
        } else if (scorePercentage > 0) {
          feedbackEl.addClass("partial");
        } else {
          feedbackEl.addClass("incorrect");
        }
        feedbackEl.addClass("visible");
        feedbackEl.createEl("div", {
          cls: "feedback-text",
          text: result.feedback
        });
      }
    });
    const buttonRow = formEl.createEl("div", { cls: "test-document-actions" });
    const markButton = buttonRow.createEl("button", {
      text: "Mark",
      cls: "test-button mark-button"
    });
    markButton.type = "button";
    markButton.onclick = () => this.handleMarkButtonClick();
    const resetButton = buttonRow.createEl("button", {
      text: "Reset",
      cls: "test-button reset-button"
    });
    resetButton.type = "button";
    resetButton.onclick = () => this.handleResetButtonClick();
    if (this.scoreSummary) {
      formEl.createEl("div", {
        text: this.scoreSummary,
        cls: "score-summary"
      });
    }
    container.appendChild(formEl);
    setTimeout(() => {
      this.textareaElements.forEach((textarea) => {
        this.adjustTextareaHeight(textarea);
      });
    }, 10);
  }
  async handleMarkButtonClick() {
    var _a, _b;
    if (!this.filePath) {
      new import_obsidian2.Notice("No file path found for this test document.");
      return;
    }
    const indexedNote = this.plugin.indexedNotes.find((n) => n.filePath === this.filePath);
    if (!indexedNote) {
      new import_obsidian2.Notice("No indexed content found for this file. Cannot mark answers.");
      return;
    }
    const provider = this.plugin.settings.llmProvider;
    const apiKeys = this.plugin.settings.apiKeys;
    if (provider !== "ollama" && !apiKeys[provider]) {
      new import_obsidian2.Notice(`${this.getProviderDisplayName(provider)} API key missing. Please set it in plugin settings.`);
      return;
    }
    const noteContent = indexedNote.content;
    const qnaPairs = this.generatedTests.map((test, idx) => ({
      question: test.question,
      answer: this.answers[idx] || "",
      type: test.type
    }));
    const spinnerOverlay = this.showSpinner();
    new import_obsidian2.Notice(`Marking in progress using ${this.getProviderDisplayName(provider)}...`);
    try {
      const feedbackArray = await markTestAnswers(
        noteContent,
        qnaPairs,
        provider,
        apiKeys,
        this.plugin.settings.models,
        this.plugin.settings.ollamaSettings
      );
      this.markResults = new Array(this.generatedTests.length).fill(null);
      feedbackArray.forEach((item) => {
        const i = item.questionNumber - 1;
        if (i >= 0 && i < this.generatedTests.length) {
          this.markResults[i] = {
            marks: item.marks,
            maxMarks: item.maxMarks,
            feedback: item.feedback
          };
        }
      });
      let totalPossibleMarks = 0;
      let totalEarnedMarks = 0;
      for (let i = 0; i < this.markResults.length; i++) {
        const result = this.markResults[i];
        if (result) {
          totalPossibleMarks += result.maxMarks;
          totalEarnedMarks += result.marks;
        }
      }
      const percentage = totalPossibleMarks ? (totalEarnedMarks / totalPossibleMarks * 100).toFixed(1) : "0.0";
      this.scoreSummary = `You scored ${totalEarnedMarks} / ${totalPossibleMarks} marks (${percentage}%)`;
      if (!this.plugin.testDocuments[this.filePath]) {
        this.plugin.testDocuments[this.filePath] = {
          description: this.description,
          questions: this.generatedTests,
          answers: {}
        };
      }
      this.plugin.testDocuments[this.filePath] = {
        ...this.plugin.testDocuments[this.filePath],
        score: parseFloat(percentage),
        markResults: this.markResults,
        answers: this.answers
      };
      await this.plugin.saveSettings();
      this.plugin.markFileAnswered(this.filePath);
      this.render();
      new import_obsidian2.Notice("Marking complete!");
    } catch (err) {
      console.error("Error marking answers:", err);
      if (err instanceof ContextLengthExceededError) {
        new import_obsidian2.Notice(`\u274C Context Length Error: ${err.message}`, 1e4);
        const errorContainer = this.containerEl.createDiv({
          cls: "error-message"
        });
        errorContainer.createEl("h3", {
          text: `Document too large for ${this.getProviderDisplayName(provider)}`
        });
        errorContainer.createEl("p", {
          text: err.message
        });
        errorContainer.createEl("p", {
          cls: "suggestion",
          text: "Suggestions: Split your document into smaller parts, or try a different LLM provider with a larger context window."
        });
        this.render();
      } else if (((_a = err.message) == null ? void 0 : _a.includes("Failed to parse")) || ((_b = err.message) == null ? void 0 : _b.includes("JSON"))) {
        const modelName = this.plugin.settings.models[provider];
        new import_obsidian2.Notice(`\u274C Model Compatibility Error: "${modelName}" failed to generate proper JSON. Try a more advanced model.`, 1e4);
        const errorContainer = this.containerEl.createDiv({
          cls: "error-message"
        });
        errorContainer.createEl("h3", {
          text: `Model Compatibility Issue: ${modelName}`
        });
        errorContainer.createEl("p", {
          text: "The model failed to generate properly structured output required for test marking."
        });
        errorContainer.createEl("p", {
          cls: "suggestion",
          text: "Some models (especially smaller or older ones) struggle with following specific JSON formatting instructions. Try using a more capable model like llama3 or gemma3, which are better at structured outputs."
        });
        this.render();
      } else {
        new import_obsidian2.Notice(`Error marking answers with ${this.getProviderDisplayName(provider)}: ${err.message}`, 5e3);
      }
    } finally {
      this.hideSpinner(spinnerOverlay);
    }
  }
  getProviderDisplayName(provider) {
    switch (provider) {
      case "openai":
        return "OpenAI";
      case "anthropic":
        return "Claude";
      case "deepseek":
        return "DeepSeek";
      case "gemini":
        return "Gemini";
      case "mistral":
        return "Mistral";
      case "ollama":
        return "Ollama";
      default:
        return provider.charAt(0).toUpperCase() + provider.slice(1);
    }
  }
  handleResetButtonClick() {
    this.answers = {};
    this.markResults = [];
    this.scoreSummary = "";
    if (!this.filePath)
      return;
    if (!this.plugin.testDocuments[this.filePath]) {
      this.plugin.testDocuments[this.filePath] = {
        description: this.description,
        questions: this.generatedTests,
        answers: {}
      };
    } else {
      this.plugin.testDocuments[this.filePath].answers = {};
    }
    delete this.plugin.testDocuments[this.filePath].score;
    this.plugin.saveSettings();
    this.plugin.markFileAnswered(this.filePath);
    this.render();
  }
  saveAnswers() {
    if (!this.filePath)
      return;
    if (!this.plugin.testDocuments[this.filePath]) {
      this.plugin.testDocuments[this.filePath] = {
        description: this.description,
        questions: this.generatedTests,
        answers: {}
      };
    }
    this.plugin.testDocuments[this.filePath].answers = this.answers;
    this.plugin.saveSettings();
    this.plugin.markFileAnswered(this.filePath);
  }
};

// src/ui/SettingsTab.ts
var import_obsidian3 = require("obsidian");
var SettingsTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian3.Setting(containerEl).setName("LLM provider").setDesc("Select which LLM provider you want to use for generating and marking tests").addDropdown((dropdown) => {
      dropdown.addOption("openai", "OpenAI").addOption("deepseek", "DeepSeek").addOption("gemini", "Google (Gemini)").addOption("mistral", "Mistral AI").addOption("ollama", "Ollama (Local)").setValue(this.plugin.settings.llmProvider === "anthropic" ? "openai" : this.plugin.settings.llmProvider).onChange(async (value) => {
        this.plugin.settings.llmProvider = value;
        await this.plugin.saveSettings();
        this.display();
      });
    });
    if (this.plugin.settings.llmProvider === "openai") {
      new import_obsidian3.Setting(containerEl).setName("OpenAI model").setDesc("Select which OpenAI model to use").addDropdown((dropdown) => {
        dropdown.addOption("gpt-3.5-turbo", "GPT-3.5 Turbo").addOption("gpt-4", "GPT-4").addOption("gpt-4-turbo", "GPT-4 Turbo").addOption("gpt-4o", "GPT-4o").setValue(this.plugin.settings.models.openai || "gpt-4").onChange(async (value) => {
          this.plugin.settings.models.openai = value;
          await this.plugin.saveSettings();
        });
      });
      new import_obsidian3.Setting(containerEl).setName("OpenAI API key").setDesc("Enter your OpenAI API key for test generation and marking").addText(
        (text) => text.setPlaceholder("sk-...").setValue(this.plugin.settings.apiKeys.openai).inputEl.type = "password"
        // Make this a password field
      ).addExtraButton((button) => {
        button.setIcon("eye").setTooltip("Toggle visibility").onClick(() => {
          var _a;
          const inputEl = (_a = button.extraSettingsEl.parentElement) == null ? void 0 : _a.querySelector("input");
          if (inputEl) {
            if (inputEl.type === "password") {
              inputEl.type = "text";
              button.setIcon("eye-off");
            } else {
              inputEl.type = "password";
              button.setIcon("eye");
            }
          }
        });
      }).addExtraButton((button) => {
        button.setIcon("save").setTooltip("Save").onClick(async () => {
          var _a;
          const inputEl = (_a = button.extraSettingsEl.parentElement) == null ? void 0 : _a.querySelector("input");
          if (inputEl) {
            this.plugin.settings.apiKeys.openai = inputEl.value;
            await this.plugin.saveSettings();
            new import_obsidian3.Notice("OpenAI API key saved");
          }
        });
      });
    }
    if (this.plugin.settings.llmProvider === "deepseek") {
      new import_obsidian3.Setting(containerEl).setName("DeepSeek model").setDesc("Select which DeepSeek model to use").addDropdown((dropdown) => {
        dropdown.addOption("deepseek-chat", "DeepSeek Chat").addOption("deepseek-coder", "DeepSeek Coder").setValue(this.plugin.settings.models.deepseek || "deepseek-chat").onChange(async (value) => {
          this.plugin.settings.models.deepseek = value;
          await this.plugin.saveSettings();
        });
      });
      new import_obsidian3.Setting(containerEl).setName("DeepSeek API key").setDesc("Enter your DeepSeek API key").addText(
        (text) => text.setPlaceholder("sk-...").setValue(this.plugin.settings.apiKeys.deepseek).inputEl.type = "password"
        // Make this a password field
      ).addExtraButton((button) => {
        button.setIcon("eye").setTooltip("Toggle visibility").onClick(() => {
          var _a;
          const inputEl = (_a = button.extraSettingsEl.parentElement) == null ? void 0 : _a.querySelector("input");
          if (inputEl) {
            if (inputEl.type === "password") {
              inputEl.type = "text";
              button.setIcon("eye-off");
            } else {
              inputEl.type = "password";
              button.setIcon("eye");
            }
          }
        });
      }).addExtraButton((button) => {
        button.setIcon("save").setTooltip("Save").onClick(async () => {
          var _a;
          const inputEl = (_a = button.extraSettingsEl.parentElement) == null ? void 0 : _a.querySelector("input");
          if (inputEl) {
            this.plugin.settings.apiKeys.deepseek = inputEl.value;
            await this.plugin.saveSettings();
            new import_obsidian3.Notice("DeepSeek API key saved");
          }
        });
      });
    }
    if (this.plugin.settings.llmProvider === "gemini") {
      new import_obsidian3.Setting(containerEl).setName("Gemini model").setDesc("Select which Gemini model to use").addDropdown((dropdown) => {
        dropdown.addOption("gemini-1.5-pro", "Gemini 1.5 Pro").addOption("gemini-1.5-flash", "Gemini 1.5 Flash").setValue(this.plugin.settings.models.gemini || "gemini-pro").onChange(async (value) => {
          this.plugin.settings.models.gemini = value;
          await this.plugin.saveSettings();
        });
      });
      new import_obsidian3.Setting(containerEl).setName("Google Gemini API key").setDesc("Enter your Google API key for Gemini").addText(
        (text) => text.setPlaceholder("API key...").setValue(this.plugin.settings.apiKeys.gemini).inputEl.type = "password"
        // Make this a password field
      ).addExtraButton((button) => {
        button.setIcon("eye").setTooltip("Toggle visibility").onClick(() => {
          var _a;
          const inputEl = (_a = button.extraSettingsEl.parentElement) == null ? void 0 : _a.querySelector("input");
          if (inputEl) {
            if (inputEl.type === "password") {
              inputEl.type = "text";
              button.setIcon("eye-off");
            } else {
              inputEl.type = "password";
              button.setIcon("eye");
            }
          }
        });
      }).addExtraButton((button) => {
        button.setIcon("save").setTooltip("Save").onClick(async () => {
          var _a;
          const inputEl = (_a = button.extraSettingsEl.parentElement) == null ? void 0 : _a.querySelector("input");
          if (inputEl) {
            this.plugin.settings.apiKeys.gemini = inputEl.value;
            await this.plugin.saveSettings();
            new import_obsidian3.Notice("Gemini API key saved");
          }
        });
      });
    }
    if (this.plugin.settings.llmProvider === "mistral") {
      new import_obsidian3.Setting(containerEl).setName("Mistral model").setDesc("Select which Mistral model to use").addDropdown((dropdown) => {
        dropdown.addOption("mistral-tiny", "Mistral Tiny").addOption("mistral-small", "Mistral Small").addOption("mistral-medium", "Mistral Medium").addOption("mistral-large-latest", "Mistral Large (Latest)").setValue(this.plugin.settings.models.mistral || "mistral-medium").onChange(async (value) => {
          this.plugin.settings.models.mistral = value;
          await this.plugin.saveSettings();
        });
      });
      new import_obsidian3.Setting(containerEl).setName("Mistral API key").setDesc("Enter your Mistral API key").addText(
        (text) => text.setPlaceholder("...").setValue(this.plugin.settings.apiKeys.mistral).inputEl.type = "password"
        // Make this a password field
      ).addExtraButton((button) => {
        button.setIcon("eye").setTooltip("Toggle visibility").onClick(() => {
          var _a;
          const inputEl = (_a = button.extraSettingsEl.parentElement) == null ? void 0 : _a.querySelector("input");
          if (inputEl) {
            if (inputEl.type === "password") {
              inputEl.type = "text";
              button.setIcon("eye-off");
            } else {
              inputEl.type = "password";
              button.setIcon("eye");
            }
          }
        });
      }).addExtraButton((button) => {
        button.setIcon("save").setTooltip("Save").onClick(async () => {
          var _a;
          const inputEl = (_a = button.extraSettingsEl.parentElement) == null ? void 0 : _a.querySelector("input");
          if (inputEl) {
            this.plugin.settings.apiKeys.mistral = inputEl.value;
            await this.plugin.saveSettings();
            new import_obsidian3.Notice("Mistral API key saved");
          }
        });
      });
    }
    if (this.plugin.settings.llmProvider === "ollama") {
      new import_obsidian3.Setting(containerEl).setName("Ollama server URL").setDesc("Enter the URL of your Ollama server").addText(
        (text) => {
          var _a;
          return text.setPlaceholder("http://localhost:11434").setValue(((_a = this.plugin.settings.ollamaSettings) == null ? void 0 : _a.url) || "http://localhost:11434").onChange(async (value) => {
            if (!this.plugin.settings.ollamaSettings) {
              this.plugin.settings.ollamaSettings = { url: value };
            } else {
              this.plugin.settings.ollamaSettings.url = value;
            }
            await this.plugin.saveSettings();
          });
        }
      );
      new import_obsidian3.Setting(containerEl).setName("Ollama model").setDesc("Enter the name of the Ollama model to use").addText(
        (text) => text.setPlaceholder("llama3").setValue(this.plugin.settings.models.ollama || "llama3").onChange(async (value) => {
          this.plugin.settings.models.ollama = value;
          await this.plugin.saveSettings();
        })
      );
      const providerInfoDiv2 = containerEl.createDiv({ cls: "provider-info" });
      providerInfoDiv2.createEl("p", {
        text: "Ollama lets you run LLMs locally. Make sure Ollama is installed and running before using this option."
      });
      providerInfoDiv2.createEl("p", {
        text: "Download Ollama from: https://ollama.com/"
      });
      providerInfoDiv2.createEl("p", {
        text: "Common models: llama3, mistral, gemma, codellama, llama3:8b, etc."
      });
      providerInfoDiv2.createEl("p", {
        text: "Run 'ollama pull [model]' in your terminal to download models before using them with this plugin."
      });
    }
    new import_obsidian3.Setting(containerEl).setName("About API keys").setHeading();
    const apiInfoDiv = containerEl.createDiv({ cls: "api-key-info" });
    apiInfoDiv.createEl("p", {
      text: "Your API keys are stored locally in your vault and are only used to communicate with the selected LLM provider."
    });
    const providerInfoDiv = containerEl.createDiv({ cls: "provider-info" });
    if (this.plugin.settings.llmProvider === "openai") {
      providerInfoDiv.createEl("p", {
        text: "OpenAI API keys can be obtained from: https://platform.openai.com/account/api-keys"
      });
      providerInfoDiv.createEl("p", {
        text: "GPT-4 and GPT-4o provide the best results but require a higher API usage tier."
      });
    } else if (this.plugin.settings.llmProvider === "deepseek") {
      providerInfoDiv.createEl("p", {
        text: "DeepSeek API keys can be obtained from the DeepSeek website."
      });
    } else if (this.plugin.settings.llmProvider === "gemini") {
      providerInfoDiv.createEl("p", {
        text: "Google Gemini API keys can be obtained from Google AI Studio: https://makersuite.google.com/app/apikey"
      });
      providerInfoDiv.createEl("p", {
        text: "Gemini 1.5 Pro offers a larger context window and improved capabilities over Gemini Pro."
      });
    } else if (this.plugin.settings.llmProvider === "mistral") {
      providerInfoDiv.createEl("p", {
        text: "WARNING: Mistral is currently not effective at marking answers"
      });
      providerInfoDiv.createEl("p", {
        text: "Mistral API keys can be obtained from: https://console.mistral.ai/api-keys/"
      });
      providerInfoDiv.createEl("p", {
        text: "Mistral offers several model sizes with different capabilities and pricing. Mistral Medium provides a good balance of performance and cost."
      });
    }
  }
};

// main.ts
var DEFAULT_SETTINGS = {
  mySetting: "default",
  llmProvider: "openai",
  apiKeys: {
    openai: "",
    anthropic: "",
    deepseek: "",
    gemini: "",
    mistral: "",
    ollama: ""
  },
  models: {
    openai: "gpt-4",
    anthropic: "claude-3-opus-20240229",
    deepseek: "deepseek-chat",
    gemini: "gemini-pro",
    mistral: "mistral-medium",
    ollama: "llama3"
  },
  ollamaSettings: {
    url: "http://localhost:11434"
  }
};
var ObsidianTestPlugin = class extends import_obsidian4.Plugin {
  constructor() {
    super(...arguments);
    this.indexedNotes = [];
    this.testDocuments = {};
  }
  async onload() {
    await this.loadStyles();
    await this.loadSettings();
    this.registerView(VIEW_TYPE, (leaf) => new TestDashboardView(leaf, this.app, this.indexedNotes, this));
    this.registerView(QUESTION_VIEW_TYPE, (leaf) => new QuestionDocumentView(leaf, this.app, this, { description: "", questions: [] }));
    this.addRibbonIcon("flask-conical", "Test dashboard", () => this.openTestDashboard());
    this.addCommand({
      id: "open-test-dashboard",
      name: "Open test dashboard",
      callback: () => {
        this.openTestDashboard();
      }
    });
    this.addSettingTab(new SettingsTab(this.app, this));
    this.registerInterval(window.setInterval(() => {
    }, 5 * 60 * 1e3));
  }
  onunload() {
  }
  async loadStyles() {
    await this.loadData();
  }
  async loadSettings() {
    const data = await this.loadData();
    if (data) {
      this.settings = Object.assign({}, DEFAULT_SETTINGS, data.settings);
      this.indexedNotes = data.persistedIndex || [];
      this.testDocuments = data.testDocuments || {};
    } else {
      this.settings = DEFAULT_SETTINGS;
      this.indexedNotes = [];
      this.testDocuments = {};
    }
  }
  async saveSettings() {
    const data = {
      settings: this.settings,
      persistedIndex: this.indexedNotes,
      testDocuments: this.testDocuments
    };
    await this.saveData(data);
  }
  async indexTestNotes() {
    this.indexedNotes = [];
    const markdownFiles = this.app.vault.getFiles();
    for (const file of markdownFiles) {
      if (!file.path.endsWith(".md"))
        continue;
      const content = await this.app.vault.read(file);
      this.indexedNotes.push({
        filePath: file.path,
        content,
        testStatus: { testsReady: true, passed: 0, total: 0 }
      });
    }
    await this.saveSettings();
    const dashLeaf = this.app.workspace.getLeavesOfType(VIEW_TYPE)[0];
    if ((dashLeaf == null ? void 0 : dashLeaf.view) instanceof TestDashboardView) {
      dashLeaf.view.pluginData = this.indexedNotes;
      dashLeaf.view.render();
    }
    new import_obsidian4.Notice(`Indexed ${this.indexedNotes.length} notes`);
    return this.indexedNotes;
  }
  openTestDashboard() {
    const existingLeaves = this.app.workspace.getLeavesOfType(VIEW_TYPE);
    if (existingLeaves.length > 0) {
      this.app.workspace.revealLeaf(existingLeaves[0]);
      return;
    }
    const leaf = this.app.workspace.getLeftLeaf(false);
    if (!leaf) {
      new import_obsidian4.Notice("Could not obtain workspace leaf.");
      return;
    }
    leaf.setViewState({ type: VIEW_TYPE, active: true });
    this.app.workspace.revealLeaf(leaf);
  }
  markFileAnswered(filePath) {
    const dashLeaf = this.app.workspace.getLeavesOfType("rag-test-view")[0];
    if ((dashLeaf == null ? void 0 : dashLeaf.view) instanceof TestDashboardView) {
      dashLeaf.view.render();
    }
  }
  openQuestionDoc(filePath) {
    if (!this.testDocuments[filePath]) {
      new import_obsidian4.Notice("No tests found for this note. Generate tests first.");
      return;
    }
    const response = this.testDocuments[filePath];
    const existingLeaves = this.app.workspace.getLeavesOfType(QUESTION_VIEW_TYPE);
    let leaf;
    if (existingLeaves.length > 0) {
      leaf = existingLeaves[0];
    } else {
      leaf = this.app.workspace.getLeaf("tab");
    }
    leaf.setViewState({ type: QUESTION_VIEW_TYPE, active: true });
    this.app.workspace.revealLeaf(leaf);
    setTimeout(() => {
      const view = leaf.view;
      if (view) {
        view.filePath = filePath;
        view.description = response.description;
        view.generatedTests = response.questions;
        view.answers = response.answers || {};
        if (response.markResults && response.markResults.length > 0) {
          view.markResults = response.markResults;
          if (typeof response.score === "number") {
            const markResults = response.markResults || [];
            let totalEarnedMarks = 0;
            let totalPossibleMarks = 0;
            markResults.forEach((result) => {
              if (result) {
                totalEarnedMarks += result.marks;
                totalPossibleMarks += result.maxMarks;
              }
            });
            view.scoreSummary = `You scored ${totalEarnedMarks} / ${totalPossibleMarks} marks (${response.score.toFixed(1)}%)`;
          }
        }
        view.render();
      }
    }, 200);
  }
};


/* nosourcemap */